export enum EventType {
  MOVE = "MOVE",
  SIMPLE_MESSAGE = "SIMPLE_MESSAGE",
  NEW_GAME = "NEW_GAME",
  GET_USERS_ONLINE = "GET_USERS_ONLINE",
  USER_NOT_ONLINE = "USER_NOT_ONLINE",
  NEW_GAME_REQUEST = "NEW_GAME_REQUEST",
  USER_DATA = "USER_DATA",
  NEW_GAME_ACCEPT = "NEW_GAME_ACCEPT",
  GET_GAME = "GET_GAME"
}