export enum StatusCode{
    USERS_ONLINE = "USERS_ONLINE",
    NEW_CHALLENGE = "NEW_CHALLENGE",
    NEW_GAME = "NEW_GAME",
    GET_GAME = "GET_GAME",
    NEW_MESSAGE = "NEW_MESSAGE",
    ALL_MESSAGES = "ALL_MESSAGES"
}